name: Build

on:
    push:
        branches: [main]
    pull_request:

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: 🗄️ Setup Rust cache
              uses: actions/cache@v2
              with:
                  key: rust-cache
                  path: |
                      ~/.cargo/registry/index
                      ~/.cargo/registry/cache
                      ~/.cargo/git
                      ./target

            - name: 🍃 Install PNPM
              uses: pnpm/action-setup@v2
              with:
                  version: latest
                  run_install: false

            - name: 🍃 Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'
                  cache: pnpm
                  cache-dependency-path: |
                      frontend/pnpm-lock.yaml

            - name: 🦀 Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            - name: 🔌 Install Node.js dependencies
              run: cd frontend && pnpm install

            - name: 🔌 Download Rust dependencies
              run: cargo fetch

            - name: Build the app
              uses: tauri-apps/tauri-action@v0

            - name: 🚀 Upload Windows MSI
              if: matrix.settings.host == 'windows-latest'
              uses: actions/upload-artifact@v3
              with:
                  name: Commit.msi
                  path: |
                      target/release/bundle/msi/*.msi
